# See https://wiki.hypr.land/Configuring/Monitors/
monitor=,preferred,auto,auto

# monitor=HDMI-A-3,3840x2160@60,0x0,1,bitdepth,10,cm,hdr
# If SDR content looks dim or washed out in HDR mode, use:
# monitor=HDMI-A-3,3840x2160@60,0x0,1,bitdepth,10,cm,hdr,sdrbrightness,1.2,sdrsaturation,0.98

monitorv2 {
  output = HDMI-A-3
  mode = preferred
  position = 0x0
  scale = 1

  bitdepth = 10
  cm = hdr
  supports_wide_color = 1
  supports_hdr = 1

  sdr_min_luminance = 0.005
  sdr_max_luminance = 200
  sdr_eotf = srgb
}

render {
  cm_fs_passthrough = true
}
